### ISSUE TITLE
更好的 Laravel 加速选择

### ISSUE THREAD

**Issue by mouyong** [JieAnthony/laravel-octane-workerman#39]
项目：https://github.com/joanhey/AdapterMan

见说明：https://www.workerman.net/q/9831 、https://github.com/walkor/workerman/issues/824

支持 laravel session 模式：https://github.com/joanhey/AdapterMan/issues/1

**Comment by jiangslee** [comment]
geilivable

**Comment by mouyong** [comment]
https://www.workerman.net/a/1512

使用 adapterman 时存在一些问题（已忘记具体问题），切换到 laraman 后可完美使用。
