### ISSUE TITLE
此项目还在维护么？

### ISSUE THREAD

**Issue by maliang** [JieAnthony/laravel-octane-workerman#40]

**Comment by mouyong** [comment]
暂时没有。存在部分问题，解决能力不足

**Comment by maliang** [comment]
> 暂时没有。存在部分问题，解决能力不足

主要是什么样的问题，能说说么？

**Comment by mouyong** [comment]
一个是在使用 dcat-admin 时，session 登录，无法正确登录进去。这是 web 方面的应用。

一个是在写长驻类型项目时，遇到了错误会导致进程不断重启，并且不断输出庞大的错误日志。

这两个问题都可能是因为我技术不到家，代码上的问题。但是我排查失败，无从下手解决。

**Comment by pifeifei** [comment]
我克隆一份， 试试看能不能解决， 我可能去适配 7.4，  laravel 8.x
