### ISSUE TITLE
MySQL连接数会一直保留,不会回收

### ISSUE THREAD

**Issue by pixiaoxiao** [JieAnthony/laravel-octane-workerman#8]
高并发情况下,请求建立的MySQL连接数会一直保留,不会回收,达MySQL配置的最大链接数之后,后续的请求一直报数据库链接错误

**Comment by mouyong** [comment]
@pixiaoxiao 此问题怎么复现呢？

**Comment by pixiaoxiao** [comment]
@mouyong  修改mysql配置把最大链接数改小 (比如200),重启mysql,jmeter测试配置请求总数大于200即可

**Comment by JieAnthony** [comment]
@pixiaoxiao 有没有报错

**Comment by pixiaoxiao** [comment]
@JieAnthony  我后来拉了你的开发版,测试的结果还是mysql的链接数一直不会回收,不回收MySQL链接的话肯定是个大问题

**Comment by pixiaoxiao** [comment]
@JieAnthony  结果是可以预见的,MySQL的的最大链接数被占用完了,MySQL新的链接请求进来,肯定会被拒绝的

**Comment by pixiaoxiao** [comment]
@JieAnthony  我对比了webman和laravel-octane-swoole 他们就没出出现这种问题

**Comment by mouyong** [comment]
> jmeter

@pixiaoxiao 代码部分直接 `\DB::connection($key)->select('select 1');` 能复现吗

**Comment by pixiaoxiao** [comment]
@mouyong  mysql 使用  show status like "max%connections "  查询同时使用的连接的最大数量

**Comment by pixiaoxiao** [comment]
@mouyong   \DB::connection($key)->select('select 1');  我没在这里调试 我是直接使用 show status like 'max%connections'; 查询同时使用的连接的最大数量

**Comment by Zsfzy** [comment]
这个问题我也遇到了

**Comment by mouyong** [comment]
@Zsfzy 方便加群后，沟通下时间，远程协助复现问题吗？

**Comment by mouyong** [comment]
@Zsfzy 项目做了一定的变动，请求结束后，不再持续占用连接的内存。方便有空测试下吗
